'use strict';

module.exports = {
  title: 'Joker Chen',

  templatePath: 'scripts/templates/index.template.html',
  siteResourcesPath: 'assets/js/Config/SiteResources.js',

  generatedNotice: '<!-- AUTO-GENERATED by scripts/generate_index_pages.js. Edit scripts/templates/index.template.html instead. -->',

  /*
    所有需要维护的 index.html 入口统一写在这里。

    支持三种写法：
    1. { route: '' }
       生成根目录 index.html

    2. { sitePage: 'resume' }
       从 SiteResources.pages.resume.route 读取路径，例如 about/

    3. { route: 'schedule/my_timetable/' }
       直接指定静态入口路径
  */
  entries: [
    {
      route: '',
      routeEntry: false
    },

    {
      sitePage: 'resume',
      routeEntry: true
    },
    {
      sitePage: 'schedule',
      routeEntry: true
    },
    {
      sitePage: 'social',
      routeEntry: true
    },
    {
      sitePage: 'life',
      routeEntry: true
    },

    {
      route: 'schedule/calendar/',
      routeEntry: true
    },
    {
      route: 'schedule/timetable/',
      routeEntry: true
    },
    {
      route: 'schedule/my_timetable/',
      routeEntry: true
    },
    {
      route: 'schedule/ustc_timetable/',
      routeEntry: true
    },

    {
      route: 'life/activities_moments/',
      routeEntry: true
    },
    {
      route: 'life/meditations/',
      routeEntry: true
    }
  ],

  /*
    Life 活动详情页从 SiteResources.activitiesMoments.dates 自动读取。
    例如 dates 中有 2026_03_20，就会生成：
    life/activities_moments/2026_03_20/index.html
  */
  activityMomentDetailEntries: {
    enabled: true,
    baseRoute: 'life/activities_moments'
  }
};
